import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../contexts/ThemeContext";
import { SidebarProvider } from "../contexts/SidebarContext";
import { WidgetProvider } from "../contexts/WidgetContext";
import { FontProvider } from "../contexts/FontContext";

const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "hello world",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.variable} font-sans antialiased`}>
				<ThemeProvider>
					<FontProvider>
						<SidebarProvider>
							<WidgetProvider>{children}</WidgetProvider>
						</SidebarProvider>
					</FontProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
